### ISSUE TITLE
error with new spawn

### ISSUE THREAD

**Issue by jcomito** [thPion/Screeps-Nooby-Guide#9] opened 2017-03-15 00:05 UTC
`TypeError: Cannot read property 'harvester' of undefined
    at StructureSpawn.spawnCreepsIfNecessary (prototype.spawn:75:70)
    at Object.module.exports.loop (main:33:32)
    at __mainLoop:1:52`

Starting a new spawn with your code. A harvester is spawned and begins collecting energy, but nothing else happens.

**Comment by DavydeVries** [comment] 2017-03-15 15:21
I think you issue is the same as #6.

**Comment by Tim-Pohlmann** [comment] 2017-03-15 18:50
duplicate of #6

**Closed as completed by Tim-Pohlmann** 2017-03-15 18:50 UTC

**Comment by jcomito** [comment] 2017-03-15 20:08
indeed, thanks. will give it a shot.
